#!/bin/python3

import math
import os
import random
import re
import sys
def solve(s):
    # Capitalize each word in the string
    capitalized_name = " ".join(word.capitalize() for word in s.split(" "))
    return capitalized_name  # Return the result instead of printing it
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = solve(s)

    fptr.write(result + '\n')

    fptr.close()
