#!/bin/python3

import math
import os
import random
import re
import sys

if __name__ == '__main__':
    n = int(input().strip())
    
    # Conditional logic to determine "Weird" or "Not Weird"
    if n % 2 == 1:  # Check if n is odd
        print("Weird")
    else:  # If n is even
        if 2 <= n <= 5:
            print("Not Weird")
        elif 6 <= n <= 20:
            print("Weird")
        elif n > 20:
            print("Not Weird")
